account/urls.py
from django.urls import path
from django.contrib.auth import views
from account.views import (ArticleList,
                           ArticleCreate,
                           ArticleUpdate,
                           ArticleDelete,
                           Profile,
                           CommentCreate,
                           CommentList,
                           SearchListArticle)

app_name = 'account'

urlpatterns = [
    path('',ArticleList.as_view(), name='home'),
    path('article/create',ArticleCreate.as_view(), name='article-create'),
    path('article/update/<int:pk>/',ArticleUpdate.as_view(), name='article-update'),
    path('article/delete/<int:pk>/',ArticleDelete.as_view(), name='article-delete'),
    path('profile/',Profile.as_view(), name='profile'),
    path('comment/create/',CommentCreate.as_view(), name='comment'),
    path('comment/',CommentList.as_view(), name='comment_list'),
    path('search/',SearchListArticle.as_view(), name='search'),
]

blog/urls.py
from django.urls import path
from .views import (ArticleList,
                    detail,CategoryList,
                    AuthorList,ArticlePreview,
                    ajax_save_comment,ajax_delete_comment,
                    SearchList,about,contactView)

app_name = 'blog'

urlpatterns = [
    path('', ArticleList.as_view(),name="home"),
    path('page/<int:page>', ArticleList.as_view(),name="home"),
    
    path('ajax-save-comment/', ajax_save_comment,name="save-comment"),
    path('ajax-delete-comment/', ajax_delete_comment,name="delete-comment"),
    
    path('article/<slug:slug>', detail,name="detail"),
    path('preview/<int:pk>', ArticlePreview.as_view(),name="preview"),
    
    path('category/<slug:slug>', CategoryList.as_view(),name="category"),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(),name="category"),
   
    path('author/<slug:username>', AuthorList.as_view(),name="author"),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(),name="author"),
   
    path('search/', SearchList.as_view(),name="search"),
    path('search/page/<int:page>', SearchList.as_view(),name="search"),
    
    path('about/', about,name="about"),
    
    path('contact/', contactView,name='contact'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from account.views import Login,activate,Register


urlpatterns = [
    path('admin-pannel-user/', admin.site.urls),
    path('', include('blog.urls')),
    
    path('', include('django.contrib.auth.urls')),
    
    path('login/', Login.as_view(), name='login'),
    path('account/', include('account.urls')),
    
    path("register/", Register.as_view(), name="register"),
    
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
    
    path('', include('django.contrib.auth.urls')),
    path('', include('social_django.urls', namespace='social')),
    
]


# show picture in admin
#from django.conf import settings
#from django.conf.urls.static import static
#urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "blog.views.page_not_found_view"

blog/models.py
from django.db import models
from django.utils import timezone
from extensions.utils import jalali_conveter
from django.core.validators import MaxValueValidator,MinValueValidator,MaxLengthValidator
from django.utils.html import format_html
from account.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField
    
class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name='آدرس آی پی')
    
    class Meta:
        verbose_name = 'آدرس آی پی'
        verbose_name_plural = 'آدرس ها'
   
    def __str__(self):
        return self.ip_address
    
class Contact(models.Model):
    name = models.CharField(max_length=35,help_text="لطفا نام و نام خانوادگی خود را وارد کنید",verbose_name="نام و نام خانوادگی")
    email = models.EmailField(verbose_name="ایمیل",help_text="ایمیل خود را وارد کنید")
    context = models.TextField(verbose_name='محتوا',help_text='متن مورد نظر خود را وارد کنید')
    
    class Meta:
        verbose_name = "مخاطب"
        verbose_name_plural = "مخاطبان"
        
    def __str__(self):
        return self.name
    
    
    
# start my managers class

class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')
    

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)
    
# end my managers class

#   start model category

class Category(models.Model):
       
    title = models.CharField(max_length = 200,verbose_name='عنوان دسته بندی',validators = [MaxLengthValidator(200,'لطفا بین 1 تا 200 حرف بنوسید')],help_text="از 1 تا 200 حرف بنویسید")
    slug = models.SlugField(max_length = 30,unique = True,verbose_name='آدرس دسته بندی',validators = [MaxLengthValidator(30,'لطفا بین 1 تا 30 حرف بنوسید')],help_text="از 1 تا 30 حرف بنویسید")
    status = models.BooleanField(default=True,verbose_name="نمایش دادن",help_text="آیا نمایش داده شود ؟")
    created = models.DateTimeField(auto_now_add = True)
    position = models.IntegerField(default=1000,validators=[MinValueValidator(1000),MaxValueValidator(1000000000)],unique=True,verbose_name="موقعیت")

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ['created']         
        
        
    def __str__(self):
        return self.title

    objects = CategoryManager()
    
#   end model category

#   start model article

class Article(models.Model):
    
    STATUS_CHOICES = (
        ('d','پیش نویس'),
        ('p','منتشر شده'),
        ('i','در حال بررسی'),
        ('b',' برگشت داده شده'),
   
    )
    
    title = models.CharField(max_length = 250,verbose_name='عنوان مقاله',help_text = 'لطفا بیشتر از 250 حرف ننویسید',validators=[MaxLengthValidator(250,"لطفا بین 1 تا 250 حرف بنویسید")])
    slug = models.SlugField(max_length = 35,unique = True,verbose_name='آدرس مقاله',help_text = 'لطفا بیشتر از 35 حرف ننویسید',validators=[MaxLengthValidator(35,"لطفا بین 1 تا 35 حرف بنویسید")])
    author = models.ForeignKey(User,null=True,on_delete=models.SET_NULL,related_name="articles",verbose_name="نویسنده",help_text="یک نویسنده کارمندی را انتخاب کنید")
    description = RichTextField(verbose_name="محتوای مقاله",help_text="محتوایی برای مقاله خود بنویسید")
    category = models.ManyToManyField(Category,verbose_name="دسته بندی",related_name="articles",help_text="کنترل یا فرمان را در مک نگه دارید تا بیش از یک مورد انتخاب شود|")
    thumbnail = models.ImageField(upload_to = 'images',verbose_name="تصویر مقاله",help_text='برای مقاله تصویری انتخاب کنید')
    publish = models.DateTimeField(default = timezone.now,verbose_name='زمان انتشار',help_text = 'فرمت صحیح تاریخ YYYY-MM-DD')
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length = 1,choices = STATUS_CHOICES,verbose_name='وضعیت',help_text="وضعیت مقاله را انتخاب کنید")
    hits = models.ManyToManyField(IPAddress,blank=True,related_name='hits',verbose_name='آدرس آی پی')
   
    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'
        ordering = ['-publish']
   
    def __str__(self):
        return self.title
    
    def jpublish(self):
        return jalali_conveter(self.publish)
    jpublish.short_description = "زمان انتشار"

    
    def thumbnail_tag(self):
        return format_html("<img src='{}' width=70px hieght=70px style='border-radius:10px'; >".format(self.thumbnail.url))
    thumbnail_tag.short_description = "تصویر مقاله"
    
    def category_to_str(self):
        return ", ".join([category.title for category in self.category.active()])
    category_to_str.short_description = "دسته بندی"
    
    def get_absolute_url(self):
        return reverse('account:home')
    
    
    objects= ArticleManager()
    
#   end model comment
#   start model comment

class Comment(models.Model):
    comment = models.CharField(max_length=10000,verbose_name="کامنت",help_text="نظر خود را بنویسید")
    user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,verbose_name="کاربر",help_text="کاربر خود را انتخاب کنید")
    active = models.BooleanField(default=False,verbose_name="فعال",help_text="در سایت نمایش داده شود ؟")
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="مقاله",help_text="لطفا یک مقاله برای نظر دادن انتخاب کنید")
    date = models.DateTimeField(default = timezone.now,verbose_name="تاریخ انتشار",help_text = 'فرمت صحیح تاریخ YYYY-MM-DD')
 
    class Meta:
        verbose_name = 'نظر'
        verbose_name_plural = 'نظر ها'
        ordering = ['-date']
   
    
    def __str__(self):
        return self.comment[:30]
    
    def jpublish(self):
        return jalali_conveter(self.date)
    jpublish.short_description = "تاریخ انتشار"

#   end model comment

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from blog.models import Article,Category,Comment,Contact
from django.core.paginator import Paginator
from django.views.generic import ListView,DetailView
from account.models import User
from django.contrib import messages
from account.mixins import AuthorAccessMixin 
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse,JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from django.core.mail import EmailMessage


class ArticleList(ListView):
    queryset = Article.objects.published()
    paginate_by = 6

    
def detail(request,slug):
    article = get_object_or_404(Article.objects.published(),slug=slug)
    context = {
        'article': article,
        'comment': Comment.objects.filter(active=True,article=article).order_by('-date'),
    }
    
    ip_address = request.user.ip_address
    if ip_address not in article.hits.all():
        article.hits.add(ip_address)
        
    return render(request,'blog/article_detail.html',context)


def ajax_save_comment(request):
    if request.method == "POST":
        pk = request.POST.get('id')
        
        comment = request.POST.get('comment')
        article = Article.objects.get(id=pk)
        user = request.user
        
        new_comment = Comment.objects.create(comment=comment,user=user,article=article,active=True)
        new_comment.save()
        
        response = 'Comment Posted'
        return HttpResponse(response)
    
    

@csrf_exempt
def ajax_delete_comment(request):
    if request.method == "POST":
        id = request.POST.get('cid')
        comment = Comment.objects.get(id=id)
        comment.delete()
        
        return JsonResponse({"status":1})
    
    else:
        return JsonResponse({"status":2})


class CategoryList(ListView):
    template_name = "blog/category_list.html"
    paginate_by = 9
    
    def get_queryset(self):
        global category
        slug  = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(),slug=slug) 
        return category.articles.published()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


class AuthorList(ListView):
    template_name = "blog/author_list.html"
    paginate_by =  9
    
    def get_queryset(self):
        global author
        username  = self.kwargs.get('username')
        author = get_object_or_404(User,username=username)  
       
        return author.articles.published()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context
    
    
class ArticlePreview(AuthorAccessMixin,DetailView):
    template_name = "blog/article_detail.html"
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article,pk=pk)


class SearchList(ListView):
    template_name = "blog/search_list.html"
    paginate_by =  9
    
    def get_queryset(self):
        global search
        search = self.request.GET.get('q')
        return Article.objects.filter(Q(description__icontains = search) | Q(title__icontains = search))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = search
        return context

def page_not_found_view(request, exception):
    return render(request, '404.html', status=404)

def about(request):
    return render(request,'blog/about.html')

def contactView(request):

    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        context = request.POST['context']
            
        contact = Contact(name=name,email=email,context=context)

        contact.save()
        messages.success(request,'بزودی با شما تماس خواهیم گرفت')

    return render(request,'blog/contact.html')
        

templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load base_tags %}
{% block title %}
| {{article.title}}        
{% endblock %}

{% block main %}
    <!-- content
    ================================================== -->
    <section class="s-content">

        <div class="row">
            <div class="column large-12">

                <article class="s-content__entry format-standard">

                    <div class="s-content__media">
                        <div class="s-content__post-thumb">
                            <img src="{{article.thumbnail.url}}" 
                                 srcset="{{article.thumbnail.url}} 2100w, 
                                         {{article.thumbnail.url}} 1050w, 
                                         {{article.thumbnail.url}} 525w" sizes="(max-width: 2100px) 100vw, 2100px" alt="{{article.title}}">
                        </div>
                    </div> <!-- end s-content__media -->

                    <div class="s-content__entry-header">
                        <h1 class="s-content__title s-content__title--post font">{{article.title}}</h1>
                        <h1 class="s-content__title font" style="font-size: 15px;" >بازدید ها :{{article.hits.count}}</h1>
                    </div> <!-- end s-content__entry-header -->

                    <div class="s-content__primary">

                        <div class="s-content__entry-content">

                            <p class="lead">
                                {{article.description|striptags|safe|linebreaks}}
                            </p> 
                  

                        </div> <!-- end s-entry__entry-content -->

                        <div class="s-content__entry-meta">

                            <div class="entry-author meta-blk">
                                <div class="author-avatar">
                                    <img class="avatar" src="{% static 'blog/images/avatars/user-06.jpg' %}" alt="user profile">
                                </div>
                                <div class="byline" style="display: flex;gap:10px">
                                    <span class="bytext">نویسنده:</span>
                                    <a href="{% url 'blog:author' article.author %}">{{article.author.get_full_name}}</a>
                                </div>
                            </div>

                            <div class="meta-bottom">
                                
                                <div class="entry-cat-links meta-blk">
                                    <div class="cat-links">
                            
                                        {% for cat in article.category.all %}
                                            <a href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a>
                                        {% endfor %}
                                    </div>

                                    <div>
                                        <span>تاریخ انتشار:
                                            <p>{{article.jpublish}}</p>
                                        </span>
                                    </div>
                                    
                                </div>

                            </div>

                        </div> <!-- s-content__entry-meta -->

                        {% popular_articles %}

                        <!-- end s-content__pagenav -->

                    </div> <!-- end s-content__primary -->
                </article> <!-- end entry -->

            </div> <!-- end column -->
        </div> <!-- end row -->


        {% if request.user.is_authenticated %}
        <!-- comments
            ================================================== -->
          
                
  
            <div id="comments-wrap">
                <div class="comment-wrapper">
                    <div id="comments" class="row">
                        <div class="column large-12">

                            <h3 class="font">{{comment.count}} نظر</h3>
                            {% if comment %}
                            <!-- START commentlist -->
                            {% for c in comment %}
                                <div class="comment-tray">
                                    <ol class="commentlist">
      
                                        <li class="depth-1 comment">

                                                    <div class="comment__avatar">
                                                        <img class="avatar" src="{{c.user.photo.url}}" alt="{{c.user.username}}" width="50" height="50">
                                                    </div>

                                                    <div class="comment__content">

                                                        <div class="comment__info">
                                                            <div class="comment__author">{{c.user.get_full_name}}</div>
                                                        </div>
                                                        <div class="comment__meta">
                                                            <div class="comment__time"> {{c.date|timesince}}  </div>
                                                            
                                                        </div>
                             
                                                        {% if user.is_superuser or request.user == c.user %} 
                                                      
                                                            <div class="comment__reply">
                                                                <input type="hidden" value="{{c.id}}">
                                                                <button class="btn-del font" style="width:50px;background:white;border:none;text-align:center;color:rgb(189, 21, 21);" data-cid="{{c.id}}" style="color:rgb(185,55,75);">حذف</button>
                                                            </div>

                                                        {% endif %}

                                                        <div class="comment__text">
                                                        <p>{{c.comment}}</p>
                                                        </div>

                                                    </div>

                                        </li> <!-- end comment level 1 -->
                                        
                                    </ol>
                                </div>
                            {% endfor %}
                            {% else %}
                            <span>نظری برای این مقاله وجود ندارد</span>
                            {% endif %} 
                            <!-- END commentlist -->

                        </div> <!-- end col-full -->
                    </div> <!-- end comments -->
                </div>

                <div class="row comment-respond">

                    <!-- START respond -->
                    <div id="respond" class="column">

                        <h3 class="font">
                        اضافه کردن نظر
                        </h3>

                        <form id="comment_form" method="post" action="{% url 'blog:detail' article.slug %}">
                            {% csrf_token %}
                            <fieldset>

                                <div class="message form-field">
                                    <input name="" type="text" id="comment" name="comment" class="h-full-width font" placeholder="نظر خود را درباره مقاله  بنویسید">
                                    <input name="" id="id" name="id" type="hidden" value="{{article.id}}">
                                </div>

                                <br>
                                <input name="submit" id="submit" class="btn btn--primary btn-wide btn--large h-full-width font" value="ارسال" type="submit">

                            </fieldset>
                        </form> <!-- end form -->

                    </div>
                    <!-- END respond-->

                </div> <!-- end comment-respond -->

            </div> <!-- end comments-wrap -->
    
        {% else %}
            <span class="font" style="background: rgb(238, 238, 238);padding:12px 0;display: block;text-align: center;">برای دیدن نظرات و همچنین  نظر دادن ابتدا باید <a href="{% url 'login' %}">وارد</a> شوید</span>
        {% endif %}

    </section> <!-- end s-content -->

{% endblock %}


{% block scr_comment %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    <script type="text/javascript">
        $(document).on('submit', '#comment_form', function(e){
            e.preventDefault()
            let _comment = $("#comment").val()
            console.log(_comment);
            
            $.ajax({
                type: "POST",
                url: "{% url 'blog:save-comment' %}",
                data: {
                    id: $('#id').val(),
                    comment: _comment,
                    csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val()
                },
                success: function(){
                    console.log('Comment passes to backend');
       
                    $('#comment').val('')
          

                let _html = '<li class="depth-1 comment">\
                                <div class="comment__avatar">\
                                    <img class="avatar" src="{{c.user.photo.url}}" alt="{{request.user.username}}" width="50" height="50">\
                                </div>\
                                <div class="comment__content">\
                                    <div class="comment__info">\
                                        <div class="comment__author">{{c.user.get_full_name}}</div>\
                                    </div>\
                                    <div class="comment__meta">\
                                        <div class="comment__time">{% now "Y" %} پیش</div>\
                                    </div>\
                                    <div class="comment__text">\
                                    <p> '+ _comment +'</p>\
                                    </div>\
                                </div>\
                            </li>\
                            '

                        $('#comment-wrapper').prepend(_html)
                        $('#comment').val('')
                        
                },

                error: function(error){
                    console.log(error);
                }

            })
        });

    //   Delete Comment
    $('.comment-wrapper').on('click', '.btn-del', function(){
        //console.log("Delete Comment Button is clicked.")

        let id = $(this).attr('data-cid')

        mydata = {
            cid:id
        }

        mythis = $(this)
        
        $.ajax({
            type: "POST",
            url: "{% url 'blog:delete-comment' %}",
            data: mydata,


            success: function(data){
                //console.log(dara);
                if(data.status === 1){
                    //console.log("comment deleted");
                    $(mythis).closest('.comment-tray').fadeOut();
                }

                if(data.status === 0){
                  //  console.log("Unable to Deleted comment");
                    alert("Unable to Deleted comment.Try again later...")
                }
            }
        })
    })
    </script>
{% endblock %}

templates/blog/article_list.html
{% extends 'blog/list.html' %}
{% load static %}

{% block previous_url %}
    {% url 'blog:home' page_obj.previous_page_number %}
{% endblock %}

{% block page_obj_number_current %}
    {% url 'blog:home' page_obj.number %}
{% endblock %}

{% block page_obj_number%}
    {% url 'blog:home' i %}
{% endblock %}

{% block num_pages_dot %}
    {% url 'blog:home' page_obj.number %}
{% endblock %}

{% block num_pages_dot_2 %}
    {% url 'blog:home' page_obj.paginator.num_pages %}
{% endblock %}

{% block next_url %}
    {% url 'blog:home' page_obj.next_page_number %}
{% endblock %}

templates/blog/author_list.html
{% extends 'blog/list.html' %}

{% block title %}
| {{author.get_full_name}}     
{% endblock %}

{% block header %}
    <!-- page header ================================================== -->
            <div class="s-pageheader">
                <div class="row">
                    <div class="column large-12">
                        <h1 class="page-title font">
                            <span class="page-title__small-type font "> نویسنده :
                            {{ author.get_full_name }}
                            </span>
                        </h1>
                    </div>
                </div>
            </div> <!-- end s-pageheader-->
{% endblock %}


{% block previous_url %}
    {% url 'blog:author' author.username page_obj.previous_page_number %}
{% endblock %}

{% block page_obj_number_current %}
    {% url 'blog:author' author.username page_obj.number %}
{% endblock %}

{% block page_obj_number%}
    {% url 'blog:author' author.username i %}
{% endblock %}

{% block num_pages_dot %}
    {% url 'blog:author' author.username page_obj.number %}
{% endblock %}

{% block num_pages_dot_2 %}
    {% url 'blog:author' author.username page_obj.paginator.num_pages %}
{% endblock %}

{% block next_url %}
    {% url 'blog:author' author.username page_obj.next_page_number %}
{% endblock %}

templates/blog/category_list.html
{% extends 'blog/list.html' %}
{% block title %}
| {{category.title}}     
{% endblock %}
{% block header %}
    <!-- page header ================================================== -->
            <div class="s-pageheader">
                <div class="row">
                    <div class="column large-12">
                        <h1 class="page-title font">
                            <span class="page-title__small-type font ">دسته بندی :
                            {{ category.title }}</span>
                        </h1>
                    </div>
                </div>
            </div> <!-- end s-pageheader-->
{% endblock %}


{% block previous_url %}
    {% url 'blog:category' category.slug page_obj.previous_page_number %}
{% endblock %}

{% block page_obj_number_current %}
    {% url 'blog:category' category.slug page_obj.number %}
{% endblock %}

{% block page_obj_number%}
    {% url 'blog:category' category.slug i %}
{% endblock %}

{% block num_pages_dot %}
    {% url 'blog:category' category.slug page_obj.number %}
{% endblock %}

{% block num_pages_dot_2 %}
    {% url 'blog:category' category.slug page_obj.paginator.num_pages %}
{% endblock %}

{% block next_url %}
    {% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

templates/blog/search_list.html
{% extends 'blog/list.html' %}
{% block title %}
| {{search}}     
{% endblock %}
{% block header %}
    <!-- page header ================================================== -->
            <div class="s-pageheader">
                <div class="row">
                    <div class="column large-12">
                        <h1 class="page-title font">
                            <span class="page-title__small-type font ">جستجو برای : {{search}}</span>
                        </h1>
                    </div>
                </div>
            </div> <!-- end s-pageheader-->
{% endblock %}


{% block previous_url %}
    {% url 'blog:search' page_obj.previous_page_number %}?q={{search}} 
{% endblock %}

{% block page_obj_number_current %}
    {% url 'blog:search' page_obj.number %}?q={{search}} 
{% endblock %}

{% block page_obj_number%}
    {% url 'blog:search' i %}?q={{search}} 
{% endblock %}

{% block num_pages_dot %}
    {% url 'blog:search' page_obj.number %}?q={{search}} 
{% endblock %}

{% block num_pages_dot_2 %}
    {% url 'blog:search' page_obj.paginator.num_pages %}?q={{search}} 
{% endblock %}

{% block next_url %}
    {% url 'blog:search' page_obj.next_page_number %}?q={{search}} 
{% endblock %}